---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SpringPassword.secretName }}
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.SpringPassword.SPRING_DATASOURCE_PASSWORD }}
type: Opaque 

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SpringURL.secretName }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.SpringURL.SPRING_DATASOURCE_URL }}
type: Opaque 

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SpringUsername.secretName }}
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.SpringUsername.SPRING_DATASOURCE_USERNAME }}
type: Opaque 

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SpringMongoURI.secretName }}
data:
  SPRING_DATA_MONGODB_URI: {{ .Values.SpringMongoURI.SPRING_DATA_MONGODB_URI }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
 name: {{ .Values.global.DockerSecret.secretName }}
data:
  .dockerconfigjson: {{ .Values.global.DockerSecret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
