---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.vpa.name }}
  labels:
    app: {{ .Values.vpa.labels }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.vpa.labels }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Values.vpa.containerPolicies.containerName }}
      resourcePolicy:
        controlledResources: {{ .Values.vpa.containerPolicies.controlledResources }}
        mode: {{ .Values.vpa.containerPolicies.mode }}
        controlledValues: {{ .Values.vpa.containerPolicies.controlledValues }}

