stages:
  - module-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend # depend required, if a child pipeline fails, we know main pipeline fails
  only:
    changes: # if changes is in frontend folder, child pipeline runs frin this folded
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend  # depend required, if a child pipeline fails, we know main pipeline fails
  only:
    changes:  # if changes is in backend folder, child pipeline runs frin this folded
      - backend/**/*

microservice-reporting:
  stage: module-pipelines
  trigger:
    include:
      - "/backend-report/.gitlab-ci.yml"
    strategy: depend  # depend required, if a child pipeline fails, we know main pipeline fails
  only:
    changes:  # if changes is in backend folder, child pipeline runs frin this folded
      - backend-report/**/*
