---
- name: upload backend unit
  copy:
    src: sausage-store-backend.service
    dest: /etc/systemd/system/sausage-store-backend.service

- name: daemon reload
  systemd:
    daemon_reload: yes

- name: start backend service
  service:
    name: sausage-store-backend
    state: started 
    enabled: true