---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
spec:
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-010-057/sausage-store/sausage-backend-report:latest
          name: report
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: 0.1
            limits:
              memory: "1025Mi"
              cpu: 0.2      
          env:
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: sausage-backend-report
                  key: STRING
          ports:
            - name: backend-report
              containerPort: 8080
      imagePullSecrets:
        - name: docker-config-secret 
