---
apiVersion: v1
kind: Secret
metadata:
  name: sausage-backend-report
data:
  STRING: bW9uZ29kYjovL3RoZWFicmFtb2ZmOlRlc3R1c3IxMjM0QHJjMWItaTUwMWs5cnV6dWJvdmIyeC5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3RoZWFicmFtb2ZmP3Rscz10cnVlJnRsc0FsbG93SW52YWxpZENlcnRpZmljYXRlcz10cnVl
type: Opaque 

# Secret for Docker Registry in GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson