---
apiVersion: v1
kind: Secret
metadata:
  name: sausage-backend
data:
  SPRING_DATASOURCE_PASSWORD: VGVzdHVzcjEyMzQ=
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi01eTlibjVzZ2VzZXdodDFsLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi90aGVhYnJhbW9mZg==
  SPRING_DATASOURCE_USERNAME: dGhlYWJyYW1vZmY=
  SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL3RoZWFicmFtb2ZmOlRlc3R1c3IxMjM0QHJjMWItaTUwMWs5cnV6dWJvdmIyeC5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE3L3RoZWFicmFtb2ZmP3Rscz10cnVl
type: Opaque 

# Secret for Docker Registry in GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson