apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  resourcePolicy:
    containerPolicies:
    - containerName: backend
      resourcePolicy:
        controlledResources: ["cpu", "memory"]
        mode: "Auto"
        controlledValues: "RequestsAndLimits"
