stages:          # List of stages for jobs, and their order of execution
  - deploy

k8s-delivery:
  stage: deploy  
  only:
    changes:
    - kubernetes/*/**
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'   #install ssh-agent for ssh auth
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan ${VM_IPADDRESS} >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "${kubeconfig}" >> config
    - scp ./config $SSH_USER@$VM_IPADDRESS:/home/$SSH_USER/
    - ssh ${SSH_USER}@${VM_IPADDRESS} 
      "
       setsid /bin/bash -s " < ./kubernetes/kube/deploy.sh
  when: manual # This setting turns a job into a manual one
  environment: #deploy-backend environment
    name: deploy-k8s/$CI_COMMIT_REF_SLUG
    url: https://{k8s_cluster}

