---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  ingressClassName: "{{ .Values.ingress.ingressClassName }}"
  tls:
  - hosts:
    - "{{ .Values.ingress.fqdn }}"
  rules:
  - host: "{{ .Values.ingress.fqdn }}"
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ .Values.ingress.service.name }}
            port:
              number: {{ .Values.ingress.service.port }}
