---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
