---
- name: create service user for frontend
  user:
    name: "{{ frontend_user }}"
    groups: sudo
    
- name: apply ssh key for the user
  authorized_key:
    user: "{{ frontend_user }}"
    key: "{{ssh_key}}"

- name: update sudoers
  copy:
    src: sudoer_frontend
    dest: /etc/sudoers.d/frontend

- name: Creates directory
  file:
    path: "{{frontend_path_default}}"
    state: directory
    mode: "0755"
    owner: "{{ frontend_user }}"